server:
  port: 8081
spring:
  cloud:
    bus:
      enabled: true
      destination: myownmanuallycreatedtopic
    stream:
      kafka:
        binder:
          autoCreateTopics: false
          zkNodes: localhost:2181
          brokers: localhost:29092
          consumer-properties:
            allow:
              auto:
                create:
                  topics: false
management:
  endpoints:
    web:
      exposure:
        include:  health, busrefresh, bus-env, refresh, env
  endpoint:
    info:
      enabled: true
logging:
  level:
    ROOT: ERROR
    com.sannette.eis.mega.*: INFO
    org.apache.kafka.*: INFO

brand: apple 
category: phones
model: iphonepro14dev
cost: 1200USD
other1: 7May1130pm
other2: 7May1145pm
